/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DnaResultsRouteImport } from './routes/dna-results'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonDayRouteImport } from './routes/lesson.$day'
import { Route as ConversationsSessionIdRouteImport } from './routes/conversations.$sessionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaResultsRoute = DnaResultsRouteImport.update({
  id: '/dna-results',
  path: '/dna-results',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonDayRoute = LessonDayRouteImport.update({
  id: '/lesson/$day',
  path: '/lesson/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsSessionIdRoute = ConversationsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ConversationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversation': typeof ConversationRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dna-results': typeof DnaResultsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/conversations/$sessionId': typeof ConversationsSessionIdRoute
  '/lesson/$day': typeof LessonDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversation': typeof ConversationRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dna-results': typeof DnaResultsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/conversations/$sessionId': typeof ConversationsSessionIdRoute
  '/lesson/$day': typeof LessonDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversation': typeof ConversationRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dna-results': typeof DnaResultsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/conversations/$sessionId': typeof ConversationsSessionIdRoute
  '/lesson/$day': typeof LessonDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversation'
    | '/conversations'
    | '/dashboard'
    | '/dna-results'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/signup'
    | '/conversations/$sessionId'
    | '/lesson/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversation'
    | '/conversations'
    | '/dashboard'
    | '/dna-results'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/signup'
    | '/conversations/$sessionId'
    | '/lesson/$day'
  id:
    | '__root__'
    | '/'
    | '/conversation'
    | '/conversations'
    | '/dashboard'
    | '/dna-results'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/signup'
    | '/conversations/$sessionId'
    | '/lesson/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationRoute: typeof ConversationRoute
  ConversationsRoute: typeof ConversationsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DnaResultsRoute: typeof DnaResultsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  SignupRoute: typeof SignupRoute
  LessonDayRoute: typeof LessonDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna-results': {
      id: '/dna-results'
      path: '/dna-results'
      fullPath: '/dna-results'
      preLoaderRoute: typeof DnaResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$day': {
      id: '/lesson/$day'
      path: '/lesson/$day'
      fullPath: '/lesson/$day'
      preLoaderRoute: typeof LessonDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$sessionId': {
      id: '/conversations/$sessionId'
      path: '/$sessionId'
      fullPath: '/conversations/$sessionId'
      preLoaderRoute: typeof ConversationsSessionIdRouteImport
      parentRoute: typeof ConversationsRoute
    }
  }
}

interface ConversationsRouteChildren {
  ConversationsSessionIdRoute: typeof ConversationsSessionIdRoute
}

const ConversationsRouteChildren: ConversationsRouteChildren = {
  ConversationsSessionIdRoute: ConversationsSessionIdRoute,
}

const ConversationsRouteWithChildren = ConversationsRoute._addFileChildren(
  ConversationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationRoute: ConversationRoute,
  ConversationsRoute: ConversationsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DnaResultsRoute: DnaResultsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  SignupRoute: SignupRoute,
  LessonDayRoute: LessonDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
